### ISSUE TITLE
csv-file is not always created

### ISSUE THREAD

**Issue by silasmahler** [adessoAG/junit-insights#11]
csv-file is not always created, needs to be tested

**Comment by florianluediger** [comment]
I have tried this with three different machines and can not reproduce the behavior you are describing. The file always gets created correctly for me.

**Comment by silasmahler** [comment]
Strange, then it might be something due to other software installations. I'll close this issue then.

**Comment by florianluediger** [comment]
It turned out that some IntelliJ settings caused this problem. Resetting the settings fixed the problem.
