### ISSUE TITLE
Nested test classes are not supported

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/junit-insights#118]
As soon as you start nesting classes, the extension does not work anymore and crashes. As a first step, it would be nice, if the extension did not crash in this case, eventually, we should support nested classes completely.

As an example, see: https://github.com/sbrannen/junit5-demo/blob/master/src/test/java/demo/BowlingGameTest.java

**Comment by cboyd10** [comment]
Hey, is there any way you could cut a release with this change included so, that I can continue to use this plugin with nested tests?

**Comment by florianluediger** [comment]
Hi Chris, I have created a new tag for the version v1.2.0 so it appears in the GitHub release overview. If you pull the dependency from jFrog as described in the README, you always get the most recent SNAPSHOT version. 

In any case, the changes from the PR should be included, if you get the newest version.
