### ISSUE TITLE
Additional dependency needed for the dependency to work

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/junit-insights#32]
When testing our jar in external projects, it was also necessary to add the following dependency to maven/gradle:

`testRuntime("org.junit.platform:junit-platform-launcher:1.1.0")`

It would be nice if this would be included as a transitive dependency.

See for example the `junit5-spring-boot` project from https://github.com/bonigarcia/mastering-junit5.

**Comment by silasmahler** [comment]
Läuft im Testprojekt
