### ISSUE TITLE
Collect timestamps in a structured way

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/junit-insights#4]
For analyzing the timestamps later, these have to be saved in a structured way.

Possible solutions:

- use java data structures at runtime
- use an in memory database
- use a database that persists the data beyond the application runtime

**Comment by silasmahler** [comment]
After some search and try-and-error it seems that the runtime data needs to be stored in the test-context or a [ParameterResolver (Example)](https://github.com/junit-team/junit5-samples/issues/29) needs to be used if dependency injection shall be used to store data in an in memory db.
Links:
https://docs.spring.io/spring/docs/current/spring-framework-reference/testing.html#testcontext-fixture-di
http://www.baeldung.com/junit-5-extensions
https://junit.org/junit5/docs/current/user-guide/#writing-tests-dependency-injection
https://github.com/junit-team/junit5-samples/blob/r5.1.0/junit5-mockito-extension/src/main/java/com/example/mockito/MockitoExtension.java
https://objectpartners.com/2016/07/26/junit-5-with-spring-boot-plus-kotlin/

**Comment by silasmahler** [comment]
Hey @florianluediger, heres the present state 👍 

**What works now/has been done:**

- Generation of database-entries for (Spring)ApplicationContextEvents + storing and reading from in-memory-db
- Generation of timemeasurements for testcontext (classes, methods) - TestBenchmarkclass
- Annotate Testclass with @JUnitInsights if you want to use the features to measure the testclass and all its methods
- Annotate Testmethods with @NoJunitInsights if you dont want to measure a certain method

**What was done why:**

- Measuring of ApplicationContexts was decoupled from measuring of Testcontexts cause it caused a ton of problems with the junit5 architecture
- in junit  extension no standard dependency injection is usable (Hence no @repository and @service -construct), so the context-store is used which problematically disappears after testexecution so the data needs to be saved properly

**What has to be done:**

- Enable @Junitinsights to also catch the applicationevents also (Could be diffecult), maybe multiple more annotations needed
- Save data for testcontexts 
- Put together all data in a similar fashion
- Generate fancy html report, but before generate something

**Comment by florianluediger** [comment]
I have looked at the use of a custom ParameterResolver for injecting the JpaRepository into the JUnit extension. Unfortunately with this approach, it is only possible to inject parameters into certain test functions or the constructor of a class. It doesn't seem to be possible to augment the `@Autowired` functinoality with this. The methods of the JUnit extension (including the constructor) are not explicitly called by our code, so changing their signature to inject the repository into them is not an option.

I will now have a look at the `publishReportEntry` function for pushing data outside of the test context.
