### ISSUE TITLE
Add option to include every test class regardless of the annotation

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/junit-insights#47]
It would be nice to have the option to just include every test class on the classpath or in a certain package in our benchmark.

This is pretty hard to do because adding an annotation or inheritance at runtime is not really possible in java. Maybe there is a workaround for this problem.

Finding all classes annotated with the `@SpringBootTest` annotation is however possible with the reflection tools java has to offer.

**Comment by silasmahler** [comment]
https://www.tutorialspoint.com/java/lang/package_isannotationpresent.htm

**Comment by florianluediger** [comment]
Maybe have a look at:

https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic
