### ISSUE TITLE
Create autoconfiguration for the application properties

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/junit-insights#48]
Resources:

- https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html
- https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-annotation-processor

There still seem to be some problems with the Kotlin support for annotation processing in Spring
https://stackoverflow.com/questions/37858833/spring-configuration-metadata-json-file-is-not-generated-in-intellij-idea-for-ko
https://github.com/spring-io/initializr/issues/438
This means the autocompletion of the library configuration can't be implemented at the moment.

**Comment by silasmahler** [comment]
Removed all configuration that isnt refactoringsafe and in the code. Library can now be tested again for compatibility, there should be less issues.

**Comment by florianluediger** [comment]
Because #59 moves the configuration from the application.properties file to the JUnit configuration, this issue is no longer relevant as soon as that is merged.
