### ISSUE TITLE
Build Gradle plugin

### ISSUE THREAD

**Issue by t-buss** [adessoAG/junit-insights#66]
Clojure for junit-insights

**Comment by t-buss** [comment]
https://docs.gradle.org/current/userguide/custom_plugins.html

**Comment by florianluediger** [comment]
Is creating a custom gradle plugin really necessary? As soon as we publish our dependency to maven central, starting the project is just a matter of adding the dependency and the autodetection system property to the gradle file. (See https://github.com/adessoAG/junit-insights/blob/master/readme.md)

This is not a particularly complex task, so I don't see why we should invest time in working on a gradle plugin.
