### ISSUE TITLE
JARs include empty "dist" folder

### ISSUE THREAD

**Issue by t-buss** [adessoAG/junit-insights#74]
Since moving the frontend files to a designated folder in deb99541e95d47f2c690f1e522dbe25dacc3e2d6 , the JARs include a empty folder. No idea where that comes from, since there is no more "dist" folder in the project

**Comment by florianluediger** [comment]
I can't find that empty folder in the jar file. Maybe try to freshly clone the project again and create the jar that way.

**Comment by florianluediger** [comment]
@t-buss have you looked into this again? Can you confirm that this is a non-issue?
