### ISSUE TITLE
Implement backend unit tests

### ISSUE THREAD

**Issue by florianluediger** [adessoAG/junit-insights#82]
Currently we have no unit tests at all. We should implement these to ensure correct behavior at all times.

**Comment by t-buss** [comment]
We also need to evaluate different testing frameworks for the frontend parts.
[Mocha](https://mochajs.org/) and [Jest](https://jestjs.io/) seem to be popular choices

**Comment by florianluediger** [comment]
I have separated frontend tests from the backend tests, see #86
